### ISSUE TITLE
create Guest Curator page and namespace

### ISSUE THREAD

**Issue by kellyhiser** [therabble/org.nashville.library.boombox#35]
Kelly or Ryan will provide copy using About markdown format when it exists.

**Comment by kellyhiser** [comment]
Text:

Guest Curator 

Ben Swank is a musician (former drummer for Soledad Brothers) and co-founder of Third Man Records in Nashville, TN. Third Man Records has been an important feature of the Nashville musical landscape since its 7th Avenue South storefront opened in 2009. Although Ben’s time as “consigliere” for Third Man Records brings him in contact with nationally and internationally renowned musical artists, he has kept a close eye on the local music scene in Nashville, making friends and contacts throughout the city.
Ben and his family are passionate supporters of the Nashville Public Library. Ben thinks that NPL BoomBox “looks and sounds wonderful.” He is excited to listen to submissions from local Nashville artists, looks forward to learning more about Nashville’s huge music scene, and is honored to have the opportunity to select 20 artists to present to the city via the NPL BoomBox platform.
NPL BoomBox and Nashville Public Library are lucky to have Ben Swank as our very first guest curator and look forward to hearing his unique perspective on some of the artists that make Nashville’s music landscape special.

**Comment by kellyhiser** [comment]
@prestonaustin please confirm that you would like this text added as a file in the style of about.hbs here: https://github.com/therabble/musicat-namespaces/tree/master/org.nashville.library_authority/org.nashville.library.boombox_ns/org.nashville.library.boombox_files/app/templates/public and I'll do so.

**Comment by prestonaustin** [comment]
@kellyhiser That is correct.

Basic practice I propose adopt for these (cc @whblondeau):
- Make a Pull Request (PR) for changes and close the requesting Issue with a link to that PR "closed by 1234"
- Shorthand here for links to PR and to other Issues takes the form # followed by the PR or Issue number, you can also paste in the whole link
- It's fine for now to close multiple issues with one PR, or have a bunch of PRs, but if editing objects right on github, one PR per object is he likely easiest path.
- Referencing issues closed by or contributed to by a PR on the PR also helps keep things clear, as it allows working the queue of PRs and figuring out what they are for "closes 1234, 1236, 1312"

**Comment by kellyhiser** [comment]
namespace created by PR https://github.com/therabble/musicat-namespaces/pull/5

@prestonaustin I'm assuming there's work needing done outside of namespacing to close this issue, so I'm leaving open.

**Comment by prestonaustin** [comment]
- [ ] Create Route
 - [ ] Create conditional to show this
 - [ ] Create Nav entries
