### ISSUE TITLE
update NBB contact email

### ISSUE THREAD

**Issue by kellyhiser** [therabble/org.nashville.library.boombox#37]
replace Ryan's email with NPLBoomBox@nashville.gov

@prestonaustin or @whblondeau can I do this myself by changing collectionContactEmail here: https://github.com/therabble/musicat-namespaces/blob/master/org.nashville.library_authority/org.nashville.library.boombox_ns/org.nashville.library.boombox_files/app/services/musicat-global.js

and here: https://github.com/therabble/musicat-namespaces/blob/master/org.nashville.library_authority/org.nashville.library.boombox_ns/org.nashville.library.boombox_files/config/environment.js

**Comment by prestonaustin** [comment]
Yep, that's correct. We'll also need to make this an authorized sender for domainadmin. We can just add that as an account using gmail settings. That generates an approval email to the address you are adding with a code you'll then need to enter to confirm it. Until that is done, we won't be able to test sends or actually send anything to that address. I'm not sure we are using it as the "From:" or "Reply-to" anywhere right now for notifications sent by the app, but we will be in the future. We'll probably replace google SMTP with something home-grown or use sendgrid or similar later, to avoid this confirmation step.

**Comment by kellyhiser** [comment]
namespace files updated: https://github.com/therabble/musicat-namespaces/pull/7

@prestonaustin I poked around in gmail with no luck - can you either make changes yourself or tell me how to do so?

**Comment by prestonaustin** [comment]
@kellyhiser - when one of these gets to a state like this (your part as done as can be) unassign yourself and assign one or both of BIll and I.

**Comment by prestonaustin** [comment]
switching notifications to sendgrid API sends, because we've outgrown gmail for this pilot
@kellyhiser, @whblondeau: I've tested the NBB From: address with sendgrid, all looks good. closing.

**Comment by fozzieblue** [comment]
@prestonaustin @kellyhiser Are we using an NPL SendGrid account? Or a Rabble SendGrid account? If it is an NPL account, can someone share login info for our records?

Thanks,

Jenny

**Comment by kellyhiser** [comment]
@fozzieblue, this is a Rabble account.

**Comment by fozzieblue** [comment]
Thanks!
