### ISSUE TITLE
change text in submission form to request one track only 

### ISSUE THREAD

**Issue by kellyhiser** [therabble/org.nashville.library.boombox#39]
specifically, the text instructing artists about uploading tracks, as it reads when all other required fields have been completed. 

Likely, this ought to be variable, so that libraries can determine how many tracks they will accept. My instinct is, though, that we can convince everyone to just accept a single track, so fine to make it this way for everyone.

**Comment by prestonaustin** [comment]
@kellyhiser  Let's create an item to go through and make the track limit logic both "one track only" and "up to n tracks" capable. It was implemented with the latter assertion, and is all kinds of ick in terms of how stuff is worded and the like in the one track case. I thought this had been cleared up with an earlier case, but a lot of the feedback is worded plural and needs recoding for the singular.
